# -*- coding: utf-8 -*-
"""IntelligentDocumentAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZI9S8v9CwRRga07sJB_7OEEFhWrDxZLR
"""

import nltk
# This line downloads the 'punkt' resource needed for sent_tokenize
try:
    nltk.data.find('tokenizers/punkt')
except nltk.downloader.DownloadError:
    nltk.download('punkt', quiet=True)

import PyPDF2
from nltk.tokenize import sent_tokenize
from google import genai
from google.colab import files

# Initialize NLTK
nltk.download('punkt')

# 4️⃣ Gemini 2.5 Flash API setup
api_key = 'GEMINI_API_KEY'
client = genai.Client(api_key=api_key)
model_name = "gemini-2.5-flash"

#Uploading PDF
print("📄 Upload your PDF file:")
uploaded = files.upload()

pdf_path = list(uploaded.keys())[0]
print("✅ PDF uploaded:", pdf_path)

pdf_text = ""
with open(pdf_path, "rb") as f:
    reader = PyPDF2.PdfReader(f)
    for page in reader.pages:
        pdf_text += page.extract_text() + "\n"

def chunk_text(text, max_words=500):
    sentences = sent_tokenize(text)
    chunks = []
    current_chunk = ""
    current_len = 0

    for sentence in sentences:
        word_count = len(sentence.split())
        if current_len + word_count > max_words:
            chunks.append(current_chunk.strip())
            current_chunk = sentence
            current_len = word_count
        else:
            current_chunk += " " + sentence
            current_len += word_count
    if current_chunk:
        chunks.append(current_chunk.strip())
    return chunks
chunks = chunk_text(pdf_text)

all_summaries = []

for i, chunk in enumerate(chunks):
    print(f"📝 Summarizing chunk {i+1}/{len(chunks)}...")

    prompt = f"""
You are an expert PDF analyzer AI.

Your tasks:
1. Summarize the text in simple English.
2. Create bullet-point notes.
3. Highlight important keywords with brief explanations.
4. Provide 5–7 helpful insights.
5. Keep output clean and easy to understand.
6. The output should be easily understandable to the user
7. Keep it well formatted
8. Include emojis for headings and key points.

TEXT TO ANALYZE:
{chunk}
"""
    response = client.models.generate_content(
        model="models/gemini-2.5-flash",
        contents=prompt
    )
    all_summaries.append(response.text)

final_summary_text = " ".join(all_summaries)
print("\n✨ FINAL PDF ANALYSIS / SUMMARY:\n")
print(final_summary_text)